targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/api/'
          output_folder: 'lib/api/generated/'
          build_only_models: true
          include_if_null: false

