name: frontend
version: 0.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  auto_route: ^7.8.4
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  http: ^1.1.2
  intl: any
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.13.5
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
